{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.backendType }}
  target:
    name: {{ .Values.externalSecrets.name }}
  dataFrom:
    - extract:
        key: {{ .Release.Name }}/server
{{- end }}

