name: Brand Scan
on:
  pull_request:
  push:
    branches: [ feature/rename-summit ]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fail on stray IntelGraph literals
        run: |
          set -euo pipefail
          ALLOW=(
            '^docs/ga/'
            '^docs/verified-deploy-readme.md$'
            '^docs/CI-CD-pinning-and-provenance-README.md$'
            '^CHANGELOG.md$'
            '^config/brand/brand.yaml$'
          )
          pattern=$(IFS='|'; echo "${ALLOW[*]}")
          # Search tracked text files for IntelGraph
          hits=$(git ls-files | grep -E '\.(ts|js|tsx|jsx|md|yml|yaml|json|html|css)$' | xargs grep -n "IntelGraph" || true)
          # Filter allowlist
          BAD=()
          while IFS= read -r line; do
            [ -z "$line" ] && continue
            file=${line%%:*}
            if echo "$file" | grep -Eq "$pattern"; then continue; fi
            BAD+=("$line")
          done <<< "$hits"
          if [ ${#BAD[@]} -gt 0 ]; then
            echo 'Found non-allowlisted IntelGraph literals:' >&2
            printf '%s\n' "${BAD[@]}" >&2
            exit 1
          fi
